### ISSUE TITLE
Clarify 'tolerance' property?

### ISSUE THREAD

**Issue by Slapbox** [mschez/react-side-bar#14]
Hey @mschez thanks for sharing this cool project!

I'm wondering what exactly `tolerance` does? I can't figure out on desktop, and I'm guessing it's a mobile-only prop, but it's not adjacent to the other mobile props so I wonder if maybe I'm misunderstanding?

Thanks again!

**Comment by mschez** [comment]
Hey!
Yes, it is a property designed for mobile devices, it is the number of pixels you have to drag the sidebar to automatically open. I mean, it you have 100px of tolerance and you only drag the the sidebar 60px from its original position the sidebar will close instead of automatically open.
Maybe you are right, it is a good point improve the README to clarify if the properties are for mobile or desktop. If you have time to do a PR, it will be welcome!

Thanks!
