### ISSUE TITLE
Might need to add a zIndex to veil initial style

### ISSUE THREAD

**Issue by puffstream** [mschez/react-side-bar#2]
Some of my elements were appearing over the veil.

I just added zIndex: 2

**Comment by mschez** [comment]
Hi,
the SideBar component accepts a *prop* for the style of veil. In this property you can set your style for the veil, for example if your want a white veil instead of black, opacity, etc.
You can use this property to set the zIndex:

```
veilStyle: {
  zIndex: 2
}
```

I think this is a good use of the component, because if I set `zIndex: 2` by default, perhaps other people needs `zIndex: 3` or `zIndex: 100`.

This solve your problem? Tell me about the result.
Thank you for your support.

**Comment by puffstream** [comment]
Thanks @mschez, that works great! Actually we decided to display: none as we want users to be able to click on the right as well.
